{
  config,
  lib,
  osConfig,
  pkgs,
  ...
}:
let
  cfg = osConfig.platform;
  emacsPackage =
    let
      candidates = map (name: lib.attrByPath [ name ] null pkgs) [
        "emacs-unstable"
        "emacs"
      ];
    in
    lib.findFirst (pkg: pkg != null) pkgs.emacs candidates;
  elispBool = value: if value then "t" else "nil";
  hostFacts = ''
    ;;; host-facts.el --- Generated by Home Manager -*- lexical-binding: t; -*-

    (defconst platform-host-slug ${builtins.toJSON cfg.host.slug})
    (defconst platform-host-title ${builtins.toJSON cfg.host.title})
    (defconst platform-host-platform ${builtins.toJSON cfg.host.platform})
    (defconst platform-host-is-darwin ${elispBool pkgs.stdenv.isDarwin})
    (defconst platform-host-is-linux ${elispBool pkgs.stdenv.isLinux})
    (defconst platform-profile-development-p ${elispBool cfg.profiles.development.enable})
    (defconst platform-profile-work-p ${elispBool cfg.profiles.work.enable})
    (defconst platform-profile-personal-p ${elispBool cfg.profiles.personal.enable})
    (defconst platform-preferred-terminal ${builtins.toJSON cfg.apps.terminal})

    (provide 'platform-host-facts)
    ;;; host-facts.el ends here
  '';
  # Eat terminal emulator sets TERM=eat-truecolor but its terminfo entries
  # only live inside the elpaca package directory. Compile them into the
  # user profile so nix-darwin's set-environment (which sets TERMINFO_DIRS
  # to include per-user profile paths) can resolve them.
  eatTerminfo = pkgs.runCommand "eat-terminfo" { nativeBuildInputs = [ pkgs.ncurses ]; } ''
    mkdir -p $out/share/terminfo
    tic -o $out/share/terminfo ${./config/eat.ti}
  '';
in
{
  config = lib.mkIf (builtins.elem "emacs" cfg.apps.enabledEditors) {
    # Install eat terminfo entries into the user profile so that
    # nix-darwin's set-environment (which sets TERMINFO_DIRS to include
    # the per-user profile) can resolve TERM=eat-truecolor.
    home.packages = [ eatTerminfo ];

    programs.emacs = {
      enable = true;
      package = emacsPackage;
    };

    services.emacs = {
      enable = true;
      client.enable = true;
      client.arguments = [
        "-c"
        "-a"
        "emacs"
      ];
    }
    // lib.optionalAttrs pkgs.stdenv.isLinux {
      startWithUserSession = "graphical";
    };

    xdg.configFile."emacs/early-init.el".source = ./config/early-init.el;
    xdg.configFile."emacs/init.el".source = ./config/init.el;
    xdg.configFile."emacs/emacs.org".source = ./config/emacs.org;
    xdg.configFile."emacs/modules" = {
      source = ./config/modules;
      recursive = true;
    };
    xdg.configFile."emacs/host-facts.el".text = hostFacts;
  };
}
