{
  config,
  lib,
  osConfig,
  pkgs,
  ...
}:
let
  cfg = osConfig.platform;
  emacsPackage =
    let
      candidates = map (name: lib.attrByPath [ name ] null pkgs) [
        "emacs-unstable"
        "emacs"
      ];
    in
    lib.findFirst (pkg: pkg != null) pkgs.emacs candidates;
  elispBool = value: if value then "t" else "nil";
  hostFacts = ''
    ;;; host-facts.el --- Generated by Home Manager -*- lexical-binding: t; -*-

    (defconst platform-host-slug ${builtins.toJSON cfg.host.slug})
    (defconst platform-host-title ${builtins.toJSON cfg.host.title})
    (defconst platform-host-platform ${builtins.toJSON cfg.host.platform})
    (defconst platform-host-is-darwin ${elispBool pkgs.stdenv.isDarwin})
    (defconst platform-host-is-linux ${elispBool pkgs.stdenv.isLinux})
    (defconst platform-profile-development-p ${elispBool cfg.profiles.development.enable})
    (defconst platform-profile-work-p ${elispBool cfg.profiles.work.enable})
    (defconst platform-profile-personal-p ${elispBool cfg.profiles.personal.enable})
    (defconst platform-preferred-terminal ${builtins.toJSON cfg.apps.terminal})

    (provide 'platform-host-facts)
    ;;; host-facts.el ends here
  '';
in
{
  config = lib.mkIf (builtins.elem "emacs" cfg.apps.enabledEditors) {
    # cmake and libtool (as glibtool) are needed to compile vterm's native module
    home.packages = [
      pkgs.cmake
      (pkgs.runCommand "glibtool-alias" { } ''
        mkdir -p $out/bin
        ln -s ${pkgs.libtool}/bin/libtool $out/bin/glibtool
        ln -s ${pkgs.libtool}/bin/libtoolize $out/bin/glibtoolize
      '')
    ];

    programs.emacs = {
      enable = true;
      package = emacsPackage;
    };

    services.emacs = {
      enable = true;
      client.enable = true;
      client.arguments = [ "-c" ];
    }
    // lib.optionalAttrs pkgs.stdenv.isLinux {
      startWithUserSession = "graphical";
    };

    xdg.configFile."emacs/early-init.el".source = ./config/early-init.el;
    xdg.configFile."emacs/init.el".source = ./config/init.el;
    xdg.configFile."emacs/emacs.org".source = ./config/emacs.org;
    xdg.configFile."emacs/banner.png".source = ./config/banner.png;
    xdg.configFile."emacs/modules" = {
      source = ./config/modules;
      recursive = true;
    };
    xdg.configFile."emacs/themes" = {
      source = ./config/themes;
      recursive = true;
    };
    xdg.configFile."emacs/host-facts.el".text = hostFacts;
  };
}
